[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install"]
workingDirectory = "server"

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "node server.js"
workingDirectory = "server"
